version: '3.4'

name: "3X03-Team37-debug"

volumes:
  mongo-data:

services:
  web:
    image: 3x03/web
    build:
      context: ..
      dockerfile: ./containers/web/Dockerfile
    env_file:
      - dev.env
    # For configuration options see https://hub.docker.com/r/tiangolo/uvicorn-gunicorn
    environment:
      - LOG_LEVEL=debug
      - VARIABLE_NAME=asgi_app
      # - MONGO_NONROOT_USERNAME
      # - MONGO_NONROOT_PASSWORD
      # - MONGO_INITDB_DATABASE
      - MAIL_USERNAME
      - MAIL_PASSWORD
      - STRIPE_SECRET_KEY
    ports:
    # TODO: use port 443 after setting up TLS
    - "5000:80"
  database:
    image: 3x03/db
    build:
      context: ..
      dockerfile: ./containers/database/Dockerfile
    volumes:
      - mongo-data:/data/db:rw
    env_file:
      - dev.env
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME
      # - MONGO_INITDB_ROOT_PASSWORD
      # - MONGO_INITDB_DATABASE
      # - MONGO_NONROOT_USERNAME
      # - MONGO_NONROOT_PASSWORD
    expose:
      - 27017
