version: '3.4'

name: "3X03-Team37-debug"

services:
  web:
    image: 3x03/web
    build:
      context: ..
      dockerfile: ./containers/web/Dockerfile
    env_file:
      - dev.env
    # For configuration options see https://hub.docker.com/r/tiangolo/meinheld-gunicorn-flask
    environment:
      - LOG_LEVEL=debug
      # - MONGO_NONROOT_USERNAME
      # - MONGO_NONROOT_PASSWORD
      # - MONGO_INITDB_DATABASE
    ports:
    # TODO: use port 443 after setting up TLS
    - "3000:443"
  database:
    image: 3x03/db
    build:
      context: ..
      dockerfile: ./containers/database/Dockerfile
    env_file:
      - dev.env
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME
      # - MONGO_INITDB_ROOT_PASSWORD
      # - MONGO_INITDB_DATABASE
      # - MONGO_NONROOT_USERNAME
      # - MONGO_NONROOT_PASSWORD
    expose:
      - 27017
